# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcd', '0002_auto_20160815_0249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name_plural': 'Notes'},
        ),
    ]
