# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcd', '0003_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noderef',
            name='node_ref',
        ),
        migrations.AlterField(
            model_name='message',
            name='producer',
            field=models.ManyToManyField(to='kcd.Node'),
        ),
        migrations.AlterField(
            model_name='multiplex',
            name='consumer',
            field=models.ManyToManyField(to='kcd.Node'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='consumer',
            field=models.ManyToManyField(to='kcd.Node'),
        ),
        migrations.DeleteModel(
            name='NodeRef',
        ),
    ]
